FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 PIP_NO_CACHE_DIR=1

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY ed_import ./ed_import
COPY sql ./sql

ENTRYPOINT ["python", "-m", "ed_import"]
CMD ["--help"]
