"""Generate sql/enums.sql from data/galaxy.schema.json.

Every low-cardinality string set of the Spansh schema becomes a native ENUM
type, preloaded with the labels the schema lists so the importer's runtime
ALTER TYPE ... ADD VALUE fallback almost never fires.

    python tools/gen_enums.py data/galaxy.schema.json > sql/enums.sql
"""
import json
import sys

schema = json.load(open(sys.argv[1], encoding="utf-8"))
ROOT = schema["items"]
MARK = "/schema/items/"


def resolve(ref):
    cur = ROOT
    for seg in ref[ref.find(MARK) + len(MARK):].split("/"):
        seg = seg.replace("~1", "/").replace("%7B", "{").replace("%7D", "}")
        cur = deref(cur)[seg]
    return cur


def deref(n):
    while isinstance(n, dict) and "$ref" in n:
        n = resolve(n["$ref"])
    return n


def node(path):
    cur = ROOT
    for seg in path.split("."):
        cur = deref(cur)
        cur = cur["items"] if seg == "[]" else cur["properties"][seg]
    return deref(cur)


def labels(n):
    n = deref(n)
    out = []
    if "enum" in n:
        out += n["enum"]
    for a in n.get("anyOf", []):
        out += labels(a)
    return [x for x in out if isinstance(x, str)]


P = ROOT["properties"]
B = node("bodies.[]")["properties"]
S = node("stations.[]")["properties"]
STATE = node("controllingFaction.state")

# type name -> (labels, comment)
TYPES = {
    "allegiance_t": (labels(P["allegiance"]), "system / station / faction allegiance"),
    "government_t": (labels(P["government"]), "government type"),
    "economy_t": (labels(P["primaryEconomy"]), "economy type"),
    "security_t": (labels(P["security"]), "system security"),
    "power_state_t": (labels(P["powerState"]), "powerplay state of a system"),
    "power_t": (labels(P["controllingPower"]), "powerplay power"),
    "faction_state_t": (labels(STATE), "faction / station controlling faction state"),
    "thargoid_state_t": (labels(node("thargoidWar.currentState")), "thargoid war state"),
    "body_type_t": (labels(B["type"]), "Planet / Star / Barycentre"),
    "body_sub_type_t": (labels(B["subType"]), "planet and star sub types"),
    "luminosity_t": (labels(B["luminosity"]), "star luminosity class"),
    "volcanism_t": (labels(B["volcanismType"]), "volcanism type"),
    "atmosphere_t": (labels(B["atmosphereType"]), "atmosphere type"),
    "terraforming_t": (labels(B["terraformingState"]), "terraforming state"),
    "reserve_level_t": (labels(B["reserveLevel"]), "ring reserve level"),
    "ring_type_t": (labels(node("bodies.[].rings.[].type")), "ring / belt type"),
    "station_type_t": (labels(S["type"]), "station type"),
    "station_state_t": (labels(S["state"]), "station state (damaged, under attack, ...)"),
    "commodity_category_t": (labels(node("stations.[].market.commodities.[].category")), "market commodity category"),
    "module_category_t": (labels(node("stations.[].outfitting.modules.[].category")), "outfitting module category"),
    "module_rating_t": (labels(node("stations.[].outfitting.modules.[].rating")), "outfitting module rating"),
}

# Sets the schema only types as free strings but which are small and stable
# in the data (measured on the 1-day dump); listed so the index keys are 4 bytes.
TYPES["material_t"] = ([
    "Antimony", "Arsenic", "Cadmium", "Carbon", "Chromium", "Germanium", "Iron", "Manganese",
    "Mercury", "Molybdenum", "Nickel", "Niobium", "Phosphorus", "Polonium", "Ruthenium",
    "Selenium", "Sulphur", "Technetium", "Tellurium", "Tin", "Tungsten", "Vanadium",
    "Yttrium", "Zinc", "Zirconium"], "raw material found on planets")
TYPES["signal_t"] = ([
    # surface signals (measured in the dumps)
    "$SAA_SignalType_Biological;", "$SAA_SignalType_Geological;", "$SAA_SignalType_Guardian;",
    "$SAA_SignalType_Human;", "$SAA_SignalType_Other;", "$SAA_SignalType_PlanetAnomaly;",
    "$SAA_SignalType_Thargoid;", "$PlanetaryMiningLocation_Name;",
    # ring hotspots: journal commodity symbols (no spaces)
    "Alexandrite", "Benitoite", "Bromellite", "Grandidierite", "LowTemperatureDiamond", "Monazite",
    "Musgravite", "Opal", "Painite", "Platinum", "Rhodplumsite", "Serendibite", "Tritium",
    "Bauxite", "Bertrandite", "Coltan", "Cryolite", "Gallite", "Indite", "Lepidolite",
    "LithiumHydroxide", "MethaneClathrate", "MethanolMonohydrateCrystals", "HydrogenPeroxide",
    "LiquidOxygen", "Water", "Osmium", "Praseodymium", "Rutile", "Samarium", "Uraninite",
    "Gold", "Silver", "Palladium", "Cobalt", "Jadeite", "Moissanite", "Pyrophyllite", "Taaffeite",
    "Beryllium", "Bismuth", "Goslarite", "Haematite", "Thorium", "Thallium",
], "planet / ring signal type (surface signals and ring hotspots)")

out = ["-- GENERATED by tools/gen_enums.py from data/galaxy.schema.json. Do not edit by hand.",
       "-- Labels missing from the schema are added at import time with ALTER TYPE ... ADD VALUE.", ""]
for name, (labs, comment) in TYPES.items():
    seen = []
    for l in labs:
        if l not in seen:
            seen.append(l)
    if not seen:
        raise SystemExit(f"no labels for {name}")
    for l in seen:
        if len(l.encode()) > 63:
            raise SystemExit(f"label too long for {name}: {l!r}")
    vals = ", ".join("'" + l.replace("'", "''") + "'" for l in seen)
    out.append(f"CREATE TYPE {name} AS ENUM ({vals});")
    out.append(f"COMMENT ON TYPE {name} IS '{comment.replace(chr(39), chr(39)*2)}';")
print("\n".join(out))
